### ISSUE TITLE
Autonumber tasks and/or expose already added ones

### ISSUE THREAD

**Issue by andrisi** [kamiyo/multi-progress-bars#2]
Tasks don't seem to show up if I don't add an "index" value, but the tool itself could add an index and thus aleviate the need to account for the tasks added and coming up with a new index. A function exposing alrady added taks (bars) would also be apreciated and in turn this could be used to come up with a new index. Thanks.

**Comment by kamiyo** [comment]
I originally had the indexes autoincrement, but the way of specifying indexes allows you to set up tasks out of order (you might want something to be the 2nd listed task, but in your workflow, it is instantiated later, for some reason). If we had it auto-increment, we'd have to decide whether to autoincrement from the last index, or auto-fill any missing rows. I supposed we could just append to the end.

Adding a way to get tasks based on indices and/or indexes based on task name is no problem.

**Comment by kamiyo** [comment]
Implemented in latest commit: f6b1d377bbd576045426387040d4025a05723005

Published on npm as v3.2.0
