### ISSUE TITLE
Chalk problem

### ISSUE THREAD

**Issue by salk52** [kamiyo/multi-progress-bars#21]
Line 1 in multi-progress-bars.mjs 

import { green } from 'chalk';

throws exception

import { green } from 'chalk';
         ^^^^^
SyntaxError: Named export 'green' not found. The requested module 'chalk' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

I'm using node 16

so it should be 

import chalk from 'chalk';
const { green } = chalk;

**Comment by kamiyo** [comment]
Duplicate of #18. Actually fixed on `4.2.2-0` prerelease, but I haven't had time to push an actual release out. I'll notify you when I do.

**Comment by salk52** [comment]
ah, sry, my mistake...

thanx

**Comment by kamiyo** [comment]
No worries, wasn't clear from the title of that issue that the problem was the same. Enjoy!
