### ISSUE TITLE
Process is not terminated remains null after bar is finished and program terminated.

### ISSUE THREAD

**Issue by Inrixia** [kamiyo/multi-progress-bars#3]
After terminating the process with Ctrl-C it does not actually close and timers continue to run in the background before erroring when trying to write to console.

This behaviour is not seen when disabling the progress bars and only requires a new instance of the MultiProgressBars class to be created. Its not affected by calling .close or .cleanup.

You can checkout the codebase I'm trying to use it in here: https://github.com/Inrixia/Floatplane-Downloader/tree/5dae0aa57be48cbb87bebc0bfa4f2c3fcad18eef

![image](https://user-images.githubusercontent.com/6373693/110237161-1ee84c00-7f9f-11eb-8d25-8fe620b3d10c.png)

**Comment by kamiyo** [comment]
I'll take a look. Seems I might have forgotten to call the cleanup code in the virtual-console from the multi-progress-bars class.

**Comment by Inrixia** [comment]
I thought so too, but debugging it it seems to still be called which was very confusing. From the looks of things everything works fine dealing with redirecting the console after close and its a issue with SIGINT from crl-c. As for why the process continues in the background but with console as null I'm lost.

**Comment by kamiyo** [comment]
Hey, I saw this github issue: https://github.com/nodejs/node/issues/9050

At first, I thought it was because of a loop, but actually, I think it's because I need to actually call process.exit() in cleanup().

I'm going to build and push a new version out, let me know if it solves the problem.

**Comment by kamiyo** [comment]
Published as multi-progress-bars@3.2.2

**Comment by Inrixia** [comment]
Looks like that fixed it! Thanks <3
