### ISSUE TITLE
Partial loading bar symbols don't display correctly on windows terminals.

### ISSUE THREAD

**Issue by Inrixia** [kamiyo/multi-progress-bars#4]
The symbols used for showing partial bits of a loading bar are not supported in windows terminals (at least in cmd), would be good to have some sort of fallback so it doesnt look broken.

![image](https://user-images.githubusercontent.com/6373693/111020738-e2986e00-842c-11eb-8c10-3614568b7ba1.png)
@Hezkezl

**Comment by kamiyo** [comment]
Hrm, are you using Windows Terminal? or just cmd.exe? cmd.exe is unable to display all unicode characters unless you switch the character page. See this stack: https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window#answer-57134096

I would personally switch to using something like ConEmu or Windows Terminal, but I will definitely put something in the README about this, or perhaps an option switch for if you know you're going to be using a terminal that doesn't support all of unicode.

**Comment by Hezkezl** [comment]
This was done using cmd.exe in Windows 10. I tried the utf-8 beta region thing from that stack link, but still had the same issue after rebooting. Changing to Windows Terminal (which looks like it basically runs Powershell?) does show the character correctly.

**Comment by kamiyo** [comment]
Hi, I'm not sure if this really is in my control. Of course I can do the bars without the fractional bars, but I think using a modern terminal would be my suggestion. I don't think it really has to do with powershell vs cmd, more so that the windows default console doesn't handle unicode well. If you use cmd.exe in Windows Terminal, it will still show the character correctly, as does using pwsh.exe.

**Comment by Inrixia** [comment]
> Hi, I'm not sure if this really is in my...

Understandable, if there is no way for you to detect if its in a unsupported environment and drop to a more simplistic display then that's fine. Feel free to close this
