### ISSUE TITLE
Setting percentage on addTask does not apply to bar

### ISSUE THREAD

**Issue by Inrixia** [kamiyo/multi-progress-bars#6]
When creating a new bar using .addTask trying to set the percentage of the bar using 
```js
bar.addTask("/=== SUMMARY ===\\", { type: "percentage", percentage: 0.5 });
```
for example the percentage is not set.
I have to call bar.update(...) to set it.

**Comment by kamiyo** [comment]
Got it. I think the problem is line 237 in multi-progress-bars.ts, but I'll test if that fixes it and push a new version out.

**Comment by kamiyo** [comment]
check v3.2.3. Should be fixed.

**Comment by Inrixia** [comment]
Working :) Thanks <3
