### ISSUE TITLE
when stream=process.stderr and stdout is not a TTY, the MPB UI does not update-in-place, and has no colors

### ISSUE THREAD

**Issue by starpit** [kamiyo/multi-progress-bars#7]
If you update examples/exampleBottom.ts to add `stream: process.stderr` to the `new MultiProgressBar()` constructor, and then run this example in a situation where stdout is not a TTY, e.g.

```sh
node bottomInput.js > /dev/null
```

then the MultiProgressBar UI does not update in place. Instead every increment/update call results in the console scrolling. There seems to be some garbage "aN;H" added to every newline --- even though i expect no newlines.

Is it possible there a bug where the cursor control characters are always sent to stdout, even if stream is stderr? I haven't looked at your code yet to see.

**Comment by starpit** [comment]
All I can see so far is in src/virtual-console.ts, https://github.com/kamiyo/multi-progress-bars/blob/master/src/virtual-console.ts#L86-L87

Those lines refer to process.stdout, independent of whether or not stdout is actually a TTY.

**Comment by kamiyo** [comment]
Ah yes, I was mostly building this for myself and didn't consider non-TTY
stdout. I'll take a look at your PR. Thanks.

**Comment by kamiyo** [comment]
Thanks for the PR - merged and published as v3.2.4
